
-- Insert 8 stili pronti
INSERT INTO public.render_stanza_stili_pronti (nome, descrizione, emoji, tags, tipo_stanza, ordine, stile, preview_hex, config) VALUES
('Scandinavo Luminoso', 'Pareti bianche, rovere chiaro, arredo minimal', '🪵', ARRAY['bianco','legno','minimal'], 'universale', 1, 'scandinavo', '#FAF7F2',
 '{"tipo_stanza":"soggiorno","stile_target":"scandinavo","intensita":"medio","verniciatura":{"attivo":true,"colore_hex":"#FAF7F2","finitura":"opaco","applica_a":"tutte"},"pavimento":{"attivo":true,"tipo":"parquet","colore_hex":"#C8A96E","pattern":"a_correre","finitura":"spazzolato"},"arredo":{"attivo":true,"intensita_cambio":"stile_mantenendo_layout","colore_dominante":"#E8E0D0","materiale":"legno","mantieni_elettrodomestici":true},"illuminazione":{"attivo":true,"tipo":"lampadario","temperatura":"warm","intensita_luce":"media"},"soffitto":{"attivo":false},"carta_da_parati":{"attivo":false},"rivestimento_pareti":{"attivo":false},"tende":{"attivo":true,"tipo":"sheer_leggere","colore_hex":"#F5F0E8","materiale":"lino","lunghezza":"fino_pavimento"},"restyling_cucina":{"attivo":false},"restyling_bagno":{"attivo":false}}'::jsonb),

('Industriale Urbano', 'Cemento, gres antracite, travi metalliche', '⚙️', ARRAY['grigio','metallo','industriale'], 'universale', 2, 'industriale', '#6B6B6B',
 '{"tipo_stanza":"soggiorno","stile_target":"industriale","intensita":"radicale","verniciatura":{"attivo":true,"colore_hex":"#6B6B6B","finitura":"opaco","applica_a":"tutte"},"pavimento":{"attivo":true,"tipo":"gres_porcellanato","colore_hex":"#373737","pattern":"rettilineo_dritto","finitura":"opaco"},"arredo":{"attivo":true,"intensita_cambio":"stile_mantenendo_layout","colore_dominante":"#4A4A4A","materiale":"metallo","mantieni_elettrodomestici":true},"soffitto":{"attivo":true,"tipo":"travi_legno","colore_hex":"#5C4A32"},"illuminazione":{"attivo":true,"tipo":"lampadario","temperatura":"warm","intensita_luce":"soffusa"},"carta_da_parati":{"attivo":false},"rivestimento_pareti":{"attivo":false},"tende":{"attivo":false},"restyling_cucina":{"attivo":false},"restyling_bagno":{"attivo":false}}'::jsonb),

('Verde Salvia Naturale', 'Parete accent verde salvia, parquet miele, lino greige', '🌿', ARRAY['verde','naturale','caldo'], 'universale', 3, 'bohemien', '#B2C5B0',
 '{"tipo_stanza":"soggiorno","stile_target":"bohemien","intensita":"medio","verniciatura":{"attivo":true,"colore_hex":"#FAF7F2","finitura":"opaco","applica_a":"parete_accent","colore_accento_hex":"#B2C5B0"},"pavimento":{"attivo":true,"tipo":"parquet","colore_hex":"#C8A96E","pattern":"a_correre","finitura":"opaco"},"arredo":{"attivo":false},"soffitto":{"attivo":false},"illuminazione":{"attivo":false},"carta_da_parati":{"attivo":false},"rivestimento_pareti":{"attivo":false},"tende":{"attivo":true,"tipo":"tende_a_pannello","colore_hex":"#C4B49A","materiale":"lino","lunghezza":"fino_pavimento"},"restyling_cucina":{"attivo":false},"restyling_bagno":{"attivo":false}}'::jsonb),

('Lusso Marmo Bianco', 'Marmo Carrara, pareti bianche lucide, lampadario design', '💎', ARRAY['marmo','bianco','lusso'], 'universale', 4, 'lusso', '#F0EDE8',
 '{"tipo_stanza":"soggiorno","stile_target":"lusso","intensita":"radicale","verniciatura":{"attivo":true,"colore_hex":"#FFFFFF","finitura":"satinato","applica_a":"tutte"},"pavimento":{"attivo":true,"tipo":"marmo","colore_hex":"#F0EDE8","pattern":"rettilineo_dritto","finitura":"lucido"},"arredo":{"attivo":true,"intensita_cambio":"stile_mantenendo_layout","colore_dominante":"#E8E4E0","materiale":"misto","mantieni_elettrodomestici":true},"soffitto":{"attivo":false},"illuminazione":{"attivo":true,"tipo":"lampadario","temperatura":"warm","intensita_luce":"media"},"carta_da_parati":{"attivo":false},"rivestimento_pareti":{"attivo":false},"tende":{"attivo":true,"tipo":"tendaggi_pesanti","colore_hex":"#C8B89A","materiale":"velluto","lunghezza":"fino_pavimento"},"restyling_cucina":{"attivo":false},"restyling_bagno":{"attivo":false}}'::jsonb),

('Terracotta Mediterranea', 'Cotto, pareti terracotta calda, boiserie bianca', '🏺', ARRAY['terracotta','caldo','mediterraneo'], 'universale', 5, 'bohemien', '#C66F43',
 '{"tipo_stanza":"soggiorno","stile_target":"bohemien","intensita":"medio","verniciatura":{"attivo":true,"colore_hex":"#C66F43","finitura":"opaco","applica_a":"parete_principale"},"pavimento":{"attivo":true,"tipo":"cotto","colore_hex":"#B85C38","pattern":"diagonale_45","finitura":"rustico_bocciardato"},"arredo":{"attivo":false},"soffitto":{"attivo":false},"illuminazione":{"attivo":false},"carta_da_parati":{"attivo":false},"rivestimento_pareti":{"attivo":true,"tipo":"boiserie","colore_hex":"#FAF7F2","altezza_cm":80,"parete_target":"tutte"},"tende":{"attivo":false},"restyling_cucina":{"attivo":false},"restyling_bagno":{"attivo":false}}'::jsonb),

('Cucina Moderna Bianca', 'Frontali bianchi laccati, quarzo grigio, maniglie nere', '🍳', ARRAY['cucina','bianco','moderno'], 'cucina', 6, 'moderno', '#F5F5F5',
 '{"tipo_stanza":"cucina","stile_target":"moderno","intensita":"radicale","verniciatura":{"attivo":true,"colore_hex":"#F5F5F5","finitura":"opaco","applica_a":"tutte"},"pavimento":{"attivo":true,"tipo":"gres_porcellanato","colore_hex":"#E8E8E8","pattern":"rettilineo_dritto","finitura":"opaco"},"arredo":{"attivo":false},"soffitto":{"attivo":false},"illuminazione":{"attivo":true,"tipo":"faretti","temperatura":"neutral","intensita_luce":"intensa"},"carta_da_parati":{"attivo":false},"rivestimento_pareti":{"attivo":false},"tende":{"attivo":false},"restyling_cucina":{"attivo":true,"colore_frontali_hex":"#FFFFFF","materiale_frontali":"laccato","materiale_piano":"quarzo","colore_piano_hex":"#B0B0B0","stile_maniglie":"nere_opache"},"restyling_bagno":{"attivo":false}}'::jsonb),

('Bagno Spa Luxury', 'Marmo grande formato, sanitari freestanding, oro bronzo', '🛁', ARRAY['bagno','marmo','lusso','spa'], 'bagno', 7, 'lusso', '#E8E4E0',
 '{"tipo_stanza":"bagno","stile_target":"lusso","intensita":"radicale","verniciatura":{"attivo":true,"colore_hex":"#F5F0E8","finitura":"satinato","applica_a":"tutte"},"pavimento":{"attivo":true,"tipo":"marmo","colore_hex":"#E8E4E0","pattern":"rettilineo_dritto","finitura":"lucido"},"arredo":{"attivo":false},"soffitto":{"attivo":false},"illuminazione":{"attivo":true,"tipo":"applique","temperatura":"warm","intensita_luce":"soffusa"},"carta_da_parati":{"attivo":false},"rivestimento_pareti":{"attivo":false},"tende":{"attivo":false},"restyling_cucina":{"attivo":false},"restyling_bagno":{"attivo":true,"colore_rivestimento_hex":"#E8E4E0","pattern_rivestimento":"marmo_grande","stile_sanitari":"freestanding","finitura_rubinetteria":"oro_bronzo","cambia_sanitari":true,"cambia_rubinetteria":true,"cambia_rivestimento":true}}'::jsonb),

('Japandi Minimal', 'Sabbia chiara, laminato naturale, boiserie legno greige', '🎋', ARRAY['japandi','minimal','naturale','zen'], 'universale', 8, 'japandi', '#E8E0D0',
 '{"tipo_stanza":"soggiorno","stile_target":"japandi","intensita":"medio","verniciatura":{"attivo":true,"colore_hex":"#E8E0D0","finitura":"opaco","applica_a":"tutte"},"pavimento":{"attivo":true,"tipo":"laminato","colore_hex":"#B89870","pattern":"a_correre","finitura":"opaco"},"arredo":{"attivo":true,"intensita_cambio":"stile_mantenendo_layout","colore_dominante":"#D4C9B8","materiale":"legno","mantieni_elettrodomestici":true},"soffitto":{"attivo":false},"illuminazione":{"attivo":true,"tipo":"plafoniera","temperatura":"warm","intensita_luce":"soffusa"},"carta_da_parati":{"attivo":false},"rivestimento_pareti":{"attivo":true,"tipo":"boiserie","colore_hex":"#C8B89A","altezza_cm":70,"parete_target":"tutte"},"tende":{"attivo":true,"tipo":"tende_a_rullo","colore_hex":"#D4C9B8","materiale":"lino","lunghezza":"fino_pavimento"},"restyling_cucina":{"attivo":false},"restyling_bagno":{"attivo":false}}'::jsonb);
