
INSERT INTO render_stanza_presets (categoria, codice, nome, hex, ordine) VALUES
('colore_parete', 'bianco_puro', 'Bianco puro', '#FFFFFF', 1),
('colore_parete', 'bianco_avorio', 'Avorio caldo', '#F5EDD6', 2),
('colore_parete', 'bianco_calce', 'Bianco calce', '#F2EDE4', 3),
('colore_parete', 'grigio_perla', 'Grigio perla', '#E8E4DC', 4),
('colore_parete', 'grigio_nebbia', 'Grigio nebbia', '#C8C4BC', 5),
('colore_parete', 'grigio_londrino', 'Grigio londrino', '#9B9BA0', 6),
('colore_parete', 'grigio_ardesia', 'Grigio ardesia', '#6B6B70', 7),
('colore_parete', 'grigio_carbone', 'Grigio carbone', '#454548', 8),
('colore_parete', 'beige_sabbia', 'Beige sabbia', '#D4C4AA', 9),
('colore_parete', 'tortora', 'Tortora', '#C5B8A8', 10),
('colore_parete', 'terracotta_soft', 'Terracotta soft', '#D4876A', 11),
('colore_parete', 'arancio_brucia', 'Arancio bruciato', '#C0613A', 12),
('colore_parete', 'verde_salvia', 'Verde salvia', '#8A9E7E', 13),
('colore_parete', 'verde_bosco', 'Verde bosco', '#4A6B48', 14),
('colore_parete', 'verde_menta', 'Verde menta', '#A8C8A8', 15),
('colore_parete', 'verde_oliva', 'Verde oliva', '#7A8A4A', 16),
('colore_parete', 'azzurro_polvere', 'Azzurro polvere', '#B0C4D8', 17),
('colore_parete', 'blu_cenere', 'Blu cenere', '#8494A8', 18),
('colore_parete', 'blu_navy', 'Blu navy', '#1B2A4A', 19),
('colore_parete', 'blu_cielo', 'Blu cielo chiaro', '#C8DCF0', 20),
('colore_parete', 'rosa_cipria', 'Rosa cipria', '#E8C4B4', 21),
('colore_parete', 'rosa_antico', 'Rosa antico', '#C8947A', 22),
('colore_parete', 'lilla_soft', 'Lilla soft', '#C4B4D0', 23),
('colore_parete', 'prugna', 'Prugna', '#7A4870', 24),
('colore_parete', 'giallo_miele', 'Giallo miele', '#D4B44A', 25),
('colore_parete', 'giallo_burro', 'Giallo burro', '#EDE4AA', 26),
('colore_parete', 'nero_fumo', 'Nero fumo', '#2A2A2A', 27),
('colore_parete', 'verde_bottiglia', 'Verde bottiglia', '#2D4A38', 28),
('colore_parete', 'blu_inchiostro', 'Blu inchiostro', '#1A2A5A', 29),
('colore_parete', 'bordeaux', 'Bordeaux', '#6B1A2A', 30),
('stile_arredo', 'moderno', 'Moderno', NULL, 1),
('stile_arredo', 'scandinavo', 'Scandinavo', NULL, 2),
('stile_arredo', 'industriale', 'Industriale', NULL, 3),
('stile_arredo', 'classico', 'Classico', NULL, 4),
('stile_arredo', 'rustico', 'Rustico/Country', NULL, 5),
('stile_arredo', 'minimalista', 'Minimalista', NULL, 6),
('stile_arredo', 'mediterraneo', 'Mediterraneo', NULL, 7),
('stile_arredo', 'art_deco', 'Art Déco', NULL, 8),
('stile_arredo', 'giapponese', 'Japandi', NULL, 9),
('stile_arredo', 'provenzale', 'Provenzale', NULL, 10),
('stile_arredo', 'eclettico', 'Eclettico', NULL, 11),
('stile_arredo', 'luxe_contemporaneo', 'Luxe contemporaneo', NULL, 12),
('colore_arredo', 'legno_naturale', 'Legno naturale', '#C8913A', 1),
('colore_arredo', 'bianco', 'Bianco', '#F8F8F8', 2),
('colore_arredo', 'nero', 'Nero', '#1A1A1A', 3),
('colore_arredo', 'grigio', 'Grigio', '#9E9E9E', 4),
('colore_arredo', 'noce', 'Noce scuro', '#7B4F2E', 5),
('colore_arredo', 'antracite', 'Antracite', '#454545', 6),
('colore_arredo', 'verde_salvia', 'Verde salvia', '#8A9E7E', 7),
('colore_arredo', 'velluto_blu', 'Velluto blu', '#1B3A6B', 8),
('colore_arredo', 'velluto_verde', 'Velluto verde', '#2D5A3D', 9),
('colore_arredo', 'oro_ottone', 'Oro/Ottone', '#D4A820', 10),
('illuminazione', 'caldo_2700k', 'Caldo 2700K', '#FFF0C0', 1),
('illuminazione', 'neutro_3000k', 'Neutro 3000K', '#FFF8E0', 2),
('illuminazione', 'freddo_4000k', 'Freddo 4000K', '#F0F8FF', 3),
('illuminazione', 'soffuso', 'Luce soffusa indiretta', NULL, 4),
('illuminazione', 'spot', 'Faretti a soffitto', NULL, 5),
('illuminazione', 'lampadario', 'Lampadario centrale', NULL, 6),
('illuminazione', 'led_strip', 'Strisce LED', NULL, 7),
('illuminazione', 'lampade_terra', 'Lampade a terra', NULL, 8);
