
INSERT INTO render_facciata_presets (category, name, value, hex_color, prompt_fragment, icon, sort_order, is_active)
VALUES
  ('colore_intonaco','Bianco Puro','bianco_puro','#F5F5F0','pure bright white smooth plaster — clean neutral Scandinavian appearance, maximum brightness','⬜',1,true),
  ('colore_intonaco','Bianco Antico','bianco_antico','#EDE8DC','antique warm white plaster with slight cream undertone — classic Italian residential appearance','🤍',2,true),
  ('colore_intonaco','Bianco Calce','bianco_calce','#F0EDE4','lime-white plaster — slightly chalky warm white, traditional Mediterranean appearance','🧱',3,true),
  ('colore_intonaco','Avorio Caldo','avorio_caldo','#EAD9B5','warm ivory plaster — golden-cream tone, classic Italian warm-climate residential facade','🌕',4,true),
  ('colore_intonaco','Beige Sabbia','beige_sabbia','#D4C4A8','sandy beige plaster — warm neutral tone, very common on Italian single-family homes','🏜️',5,true),
  ('colore_intonaco','Beige Tortora','beige_tortora','#C8BAAA','tortora (warm taupe-grey-beige) plaster — sophisticated warm neutral, contemporary Italian residential','🕊️',6,true),
  ('colore_intonaco','Beige Rosa','beige_rosa','#DCC0A8','pale dusty-rose beige plaster — warm pinkish-beige, traditional Tuscan and Venetian facades','🌸',7,true),
  ('colore_intonaco','Sabbia Deserto','sabbia_deserto','#C4A882','desert sand plaster — medium warm tan, contemporary residential, pairs well with stone accents','🌴',8,true),
  ('colore_intonaco','Ocra Classica','ocra_classica','#C8922A','classic ochre yellow plaster — warm saturated yellow-orange, typical Emilian and Venetian historic facades','🟡',9,true),
  ('colore_intonaco','Ocra Pallida','ocra_pallida','#D4B870','pale ochre plaster — soft light yellow-gold, traditional Italian warm-climate appearance','💛',10,true),
  ('colore_intonaco','Giallo Siena','giallo_siena','#C4A040','Sienna yellow plaster — warm golden-yellow characteristic of Tuscan hill town facades','🌻',11,true),
  ('colore_intonaco','Giallo Limone','giallo_limone','#E8D880','lemon yellow plaster — bright cheerful yellow, coastal Italian architecture','🍋',12,true),
  ('colore_intonaco','Terracotta','terracotta','#C46840','terracotta plaster — warm orange-red-brown, classic Mediterranean and Tuscan appearance','🏺',13,true),
  ('colore_intonaco','Arancio Veneziano','arancio_veneziano','#D4783A','Venetian orange plaster — warm saturated orange, characteristic of Venetian building facades','🍊',14,true),
  ('colore_intonaco','Rosso Pompeiano','rosso_pompeiano','#A83828','Pompeian red plaster — deep warm brick-red, historic Italian architectural tradition','🔴',15,true),
  ('colore_intonaco','Grigio Perla','grigio_perla','#C8C4C0','pearl grey plaster — light warm grey, very popular on contemporary Italian residential facades','🩶',16,true),
  ('colore_intonaco','Grigio Cemento','grigio_cemento','#9A9A98','concrete grey plaster — medium neutral grey, industrial-contemporary aesthetic','🏗️',17,true),
  ('colore_intonaco','Grigio Antracite','grigio_antracite','#484848','anthracite dark grey plaster — very dark grey, modern premium contemporary facades','⬛',18,true),
  ('colore_intonaco','Grigio Tortora','grigio_tortora','#A8A098','warm tortora grey — greige (grey-beige) tone, contemporary sophisticated residential','🐦',19,true),
  ('colore_intonaco','Grigio Chiaro','grigio_chiaro','#D8D4D0','light grey plaster — pale neutral grey, Scandinavian-influenced contemporary Italian','☁️',20,true),
  ('colore_intonaco','Verde Salvia','verde_salvia','#8A9878','sage green plaster — muted grey-green, organic contemporary aesthetic','🌿',21,true),
  ('colore_intonaco','Verde Bosco','verde_bosco','#4A6040','forest green plaster — deep saturated green, striking contemporary or rustic mountain aesthetic','🌲',22,true),
  ('finitura_intonaco','Liscio','liscio',NULL,'smooth flat plaster finish — perfectly flat surface with no texture, satin-smooth appearance','▬',1,true),
  ('finitura_intonaco','Graffiato fine','graffiato_fine',NULL,'fine scraped/combed plaster texture — 1.0-1.5mm grain size, uniform horizontal or circular scraping marks','≋',2,true),
  ('finitura_intonaco','Graffiato medio','graffiato_medio',NULL,'medium scraped plaster texture — 2.0-2.5mm grain, more pronounced horizontal combing marks','≡',3,true),
  ('finitura_intonaco','Rasato','rasato',NULL,'skimmed/skim-coat plaster — very fine 0.5mm texture, slightly rougher than liscio but nearly smooth','◌',4,true),
  ('finitura_intonaco','Bucciato','bucciato',NULL,'orange-peel plaster texture (bucciato) — irregular small pebble-like surface texture','🍊',5,true),
  ('finitura_intonaco','Strutturato grosso','strutturato_grosso',NULL,'coarse structured plaster — 3.0-4.0mm aggregate with pronounced rough texture and visible pebble-grain','🪨',6,true),
  ('finitura_intonaco','Rustico / Civile','rustico',NULL,'rustic rough-cast plaster — irregular rough surface with occasional aggregate exposure','🏡',7,true),
  ('finitura_intonaco','Veneziana','veneziana',NULL,'Venetian plaster (stucco veneziano) — polished multi-layer smooth plaster with subtle depth and translucency','✨',8,true),
  ('finitura_intonaco','Bugnato','bugnato',NULL,'rusticated ashlar (bugnato) plaster — regular rectangular raised blocks separated by recessed joints','⊞',9,true),
  ('rivestimento_pietra','Pietra Serena','pietra_serena','#7A8080','Pietra Serena cladding — classic Florentine blue-grey sandstone, smooth sawn finish with fine grain','🪨',1,true),
  ('rivestimento_pietra','Travertino','travertino','#D4C4A0','travertine stone cladding — cream-to-warm-beige with characteristic open-pore cross-cut surface pattern','🏛️',2,true),
  ('rivestimento_pietra','Arenaria Beige','arenaria_beige','#C8A870','beige sandstone cladding — warm sandy-beige with uniform fine-grain surface','🏜️',3,true),
  ('rivestimento_pietra','Pietra di Luserna','luserna','#686870','Luserna stone cladding — silver-grey crystalline quartzite with characteristic split-face texture','✨',4,true),
  ('rivestimento_pietra','Marmo Bianco','marmo_bianco','#F0EEEC','white marble cladding — brilliant white with fine grey veining, polished or honed finish','⬜',5,true),
  ('rivestimento_pietra','Porfido','porfido','#7A5858','porphyry stone cladding — dark red-purple volcanic stone with crystalline surface','🔴',6,true),
  ('rivestimento_pietra','Pietra Grigia Splitface','splitface_grigio','#888890','grey splitface stone cladding — rough split-face natural stone with irregular texture','🪨',7,true),
  ('rivestimento_pietra','Pietra Rustica Mista','pietra_rustica','#A09070','mixed rustic stone cladding — irregular natural stone pieces in warm mixed earth tones','🏡',8,true),
  ('rivestimento_laterizio','Cotto Rosso Classico','cotto_rosso','#A84030','classic red exposed brick cladding — warm red fired clay brick, 25cm×6cm standard Italian brick bond','🧱',1,true),
  ('rivestimento_laterizio','Clinker Rosso','clinker_rosso','#9A3828','red clinker brick cladding — high-fired vitrified brick, very dense non-porous surface','🟥',2,true),
  ('rivestimento_laterizio','Clinker Grigio','clinker_grigio','#707070','grey clinker brick cladding — high-fired grey-anthracite vitrified brick','⬜',3,true),
  ('rivestimento_laterizio','Clinker Beige','clinker_beige','#C0A878','beige/buff clinker brick cladding — warm cream-yellow high-fired brick','🟨',4,true),
  ('rivestimento_laterizio','Cotto Mattone','cotto_mattone','#8A4028','traditional Italian mattone cotto — handmade-appearance textured brick with colour variations','🏛️',5,true),
  ('rivestimento_laterizio','Laterizio Bianco','laterizio_bianco','#E0D8D0','white/cream painted or slip-coated brick — whitewashed brick appearance','⬜',6,true),
  ('cappotto_spessore','4 cm','4',NULL,'minimal thermal coat 40mm thick — very slight increase in facade projection','▏',1,true),
  ('cappotto_spessore','6 cm','6',NULL,'thermal coat 60mm thick — slight visible increase in window reveal depth','▎',2,true),
  ('cappotto_spessore','8 cm','8',NULL,'thermal coat 80mm thick — noticeable window reveal deepening of approx 80mm','▍',3,true),
  ('cappotto_spessore','10 cm','10',NULL,'standard thermal coat 100mm — window reveals clearly deeper, slight shadow on window perimeter','▌',4,true),
  ('cappotto_spessore','12 cm','12',NULL,'substantial thermal coat 120mm — clearly visible deeper window reveals','▋',5,true),
  ('cappotto_spessore','14 cm','14',NULL,'heavy thermal coat 140mm — very visible deeper reveals, thick facade profile','█',6,true),
  ('cappotto_spessore','16 cm','16',NULL,'extra-heavy thermal coat 160mm — maximum reveal depth, high-performance insulation profile','█',7,true),
  ('zona_rivestimento','Tutta la facciata','tutta',NULL,'FULL FACADE: apply specified cladding/color across the ENTIRE facade surface from ground to roofline','🏠',1,true),
  ('zona_rivestimento','Solo piano terra','piano_terra',NULL,'GROUND FLOOR ONLY: apply specified cladding/color ONLY on the ground floor level','⬇️',2,true),
  ('zona_rivestimento','Solo piani superiori','piani_sup',NULL,'UPPER FLOORS ONLY: apply specified finish ONLY on first floor and above','⬆️',3,true),
  ('zona_rivestimento','Zoccolatura (1m base)','zoccolatura',NULL,'PLINTH/SOCLE ONLY: apply specified cladding only to a 80-120cm high base zone','▁',4,true),
  ('zona_rivestimento','Cantonali (angoli)','cantonali',NULL,'CORNER QUOINS ONLY: apply specified stone/brick cladding only at the building corners','◤',5,true),
  ('zona_rivestimento','Fascia marcapiano','marcapiano',NULL,'FLOOR-SEPARATING BAND ONLY: apply specified finish as a horizontal band between floors','═',6,true);
