// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wahnkxfmgqvxfjeeuiep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhaG5reGZtZ3F2eGZqZWV1aWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NzIxNjAsImV4cCI6MjA4ODM0ODE2MH0.vMbUz6f_cBaPrf_RdO1lQcu1AHEWENVcoE5LwrfayFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});